### ISSUE TITLE
$extconfigfile missing in init.pp ?

### ISSUE THREAD

**Issue by Yamakasi** [oxc/puppet-dovecot#17]
Are we missing $extconfigfile in the init.pp so we can use extconfig and extconfigfile both ?

I'm not sure but is this based on the current dovecot design as I now use $configs to fill my dovecot-ldap.conf.ext for an example and I doubt if this is the right way.

**Comment by oxc** [comment]
I believe the readme is quite clear on how external configs work: https://github.com/oxc/puppet-dovecot/blob/master/README.md#external-config-files

I'm not totally sure which functionality you are missing, please elaborate.

**Comment by Yamakasi** [comment]
It's explained but I wondered if we should not go the dovecot way, even when it's puppetized. That's why, also refering to this quote:

> In a puppet-based setup, this should not be necessary, and is thus currently not supported by this module. 

I think it adds the flexibility which is taken out now ?

**Comment by oxc** [comment]
This quote has nothing to do with dovecot-ldap.conf.ext, so perhaps you can explain your use-case. 
Flexibility in this case comes with additional complexity, as I have explained in the original issue. If you have a use-case, that additional complexity might be warranted, but until then it's not.

**Comment by Yamakasi** [comment]
Sure it has everything todo with it otherwise you won't quote the situation. There is no specific use-case, there are standards we could adopt and indeed can add some complexity but is very doable to keep the config design/layout as native as possible.

**Comment by oxc** [comment]
No, it does not. This text you quoted is about includes in conf.d, as the readme clearly states. Please read the text before you pick it apart, and please try the examples from the readme before you complain about missing features (as you have done before). Otherwise you're just trolling, if deliberately or not.

I'm closing this, because the extconfig parameter is delegating to extconfigfile type, so this is already exactly what you want.

You're always welcome to create pull requests, of course.

**Comment by Yamakasi** [comment]
I must say it's a pity you always try to "point a finger" with a bad attitude when someone, like me in 2 cases now, mentions something to make your work more clear or try to go forward on standards, improvements, design.

Your way is a way to have the same type of config at the end but it's not like the standards of dovecot which you might want to keep in mind as it makes it indeed unclear and your comment, the quote in this "issue", creates an open end and you clearly try to "point a finger" again there which is rude and doesn't make people enthusiastic to create a PR at all.

**Comment by oxc** [comment]
If you finally care to explain what you are trying to achieve, and why you think this is not working with this module, we could have a constructive discussion, but you refuse to provide that information.

Managing external configs files like dovecot-ldap.conf.ext is totally possible from both puppet and hiera, and the readme has an example that explains how it might look like.

The readme also explains why it's necessary to have that separation in the first place, and provides a link to the dovecot manual for further reference.

It explains why this differs from the includes in conf.d and why those (and only those) are currently not supported, and what is the required prerequisite to get them supported.

I'm really not sure what more you need, and so far you have not made any attempt to clarify that. Neither have you responded to any of my remarks in my replies. 
Instead you are complaining about my tone, which - granted - is somewhat annoyed (and for good reason, see previous paragraphs), but really not the issue here.
